default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { 5432 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "okomo" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>

development:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") { "okomo_development" } %>
  queue:
    <<: *default
    database: <%= ENV.fetch("DATABASE_QUEUE_NAME") { "okomo_development_queue" } %>
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: okomo_test
  queue:
    <<: *default
    database: okomo_test_queue
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DATABASE_NAME") { "okomo_production" } %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
  queue:
    <<: *default
    database: <%= ENV.fetch("DATABASE_QUEUE_NAME") { "okomo_production_queue" } %>
    username: <%= ENV["DATABASE_USERNAME"] %>
    password: <%= ENV["DATABASE_PASSWORD"] %>
    migrations_paths: db/queue_migrate
